### ISSUE TITLE
Class review 

### ISSUE THREAD

**Issue by nallanrugby** [nallanrugby/Final_Project_Weather_Nicholas_Allan#1]
For now I need help figuring out one specific problem in one of python notebooks. This notebook in found in the bin directory named as final_project_code.

For some reason when I try to run some statistical functions in my code I receive an error that says my variable doesn't exist but when I run plot functions that variable seems to work. I haven’t specified which variables this happens for because it seems the problem can be found through out the data frame.

**Comment by ttimbers** [comment]
@taliamo adfjasdjfklad
